### ISSUE TITLE
[obscura] [checkpoint] model za teksturą trawy

### ISSUE THREAD

**Issue by Jelsuk** [DownToHellBeta/Beta#7]
Model bossa cofnął się za teksturę trawy nad drogą, która przecina go na wysokości łap i ogona. Postać gracza jest ułożona prawidłowo 
W pewnym momencie po porażce w walce z tym bossem, postać odrodziła się przy checkpointcie za areną obscury, co pozwoliło ominąć bossa. Nadal można było z nią walczyć, jeżeli się wróciło.
Po powrocie, pojawił się problem opisany jako pierwszy.

**Comment by Jelsuk** [comment]
Screenshot z błędem
https://1drv.ms/u/s!AlvrOXveiDotj2E5SHqURp_Ejt-_

**Comment by DownToHellBeta** [comment]
Błąd z trawą został poprawiony. Checkpoint za areną został usunięty.
